#!/bin/bash

set -eux

source ./grapher_functions

timestamp=$(date +"%s")
output_file="graph-${timestamp}"

counter=0
echo $counter

while [ "${counter}" -lt 10 ]
do
 slap_with_concurrency "${counter}"# >> "${output_file}"
 let counter=$((${counter} + 1))
done

while [ "${counter}" -lt 100 ]
do
 slap_with_concurrency "${counter}"# >> "${output_file}"
 let counter=$((${counter} + 1))
done
